name: rahao
channels:
  - conda-forge
  - anaconda
  - numba
  - pytorch
  - nvidia
dependencies:
  - python=3.8
  - tqdm
  - numba
  - pandas
  - numpy
  - scipy
  - matplotlib
  - cvxpy
  - pytorch==1.13.1
  - pytorch-cuda=11.6
  - pip
  - pip:
    - diffcp
